## DAY 3
### ASSIGNMENT

## QUESTION 01

### FROM THE ARRAY, RETRIVE THE VALUES([[4,5,6],[6,7,8]]) USING INDEXING.

In [1]:
import numpy as np

In [3]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[4,5,6,7,8]
arr=np.array([lst1,lst2,lst3])

In [4]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [6]:
arr[1:,2:]

array([[4, 5, 6],
       [6, 7, 8]])

## QUESTION 02

### CREATE A DATA FRAME USING np.random.randn FUNCTION WITH 5 ROWS AND 4 COLUMNS AND PERFORM VARIOUS OPERATIONS USING PANDAS LIBRARY

In [25]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randn(5,4),index=['Row1','Row2','Row3','Row4','Row5',],columns=["Column1","Column2","Column3","Column4"])
df

Column1   Column2   Column3   Column4
Row1  0.649122 -2.679288 -0.917120 -1.886787
Row2 -0.817751  0.109067 -0.058217 -0.457767
Row3  1.739710 -1.159130 -1.180192 -1.973805
Row4  1.408140 -0.226266 -0.971657  1.749641
Row5  0.113475 -0.719015  0.305388 -0.266778

In [27]:
print(df.head(2))
print()
print(df.tail(2))
print()
print(df[['Column1','Column4']])

       Column1   Column2   Column3   Column4
Row1  0.649122 -2.679288 -0.917120 -1.886787
Row2 -0.817751  0.109067 -0.058217 -0.457767

       Column1   Column2   Column3   Column4
Row4  1.408140 -0.226266 -0.971657  1.749641
Row5  0.113475 -0.719015  0.305388 -0.266778

       Column1   Column4
Row1  0.649122 -1.886787
Row2 -0.817751 -0.457767
Row3  1.739710 -1.973805
Row4  1.408140  1.749641
Row5  0.113475 -0.266778


In [28]:
print(df.loc['Row1']) #accessing elements
print()
print(type(df.loc['Row1']))
print()
print(df.iloc[2:4,1:3])

Column1    0.649122
Column2   -2.679288
Column3   -0.917120
Column4   -1.886787
Name: Row1, dtype: float64

<class 'pandas.core.series.Series'>

       Column2   Column3
Row3 -1.159130 -1.180192
Row4 -0.226266 -0.971657


In [29]:
df.iloc[:,1:].values

array([[-2.67928834, -0.9171204 , -1.88678702],
       [ 0.10906696, -0.05821678, -0.4577667 ],
       [-1.15913047, -1.18019197, -1.97380468],
       [-0.22626647, -0.97165712,  1.74964147],
       [-0.71901456,  0.3053884 , -0.26677829]])

In [30]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [31]:
df

Column1   Column2   Column3   Column4
Row1  0.649122 -2.679288 -0.917120 -1.886787
Row2 -0.817751  0.109067 -0.058217 -0.457767
Row3  1.739710 -1.159130 -1.180192 -1.973805
Row4  1.408140 -0.226266 -0.971657  1.749641
Row5  0.113475 -0.719015  0.305388 -0.266778

In [32]:
df['Column1'].unique()

array([ 0.64912179, -0.81775072,  1.73970966,  1.40813961,  0.11347503])

In [33]:
df.shape

(5, 4)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  5 non-null      float64
 1   Column2  5 non-null      float64
 2   Column3  5 non-null      float64
 3   Column4  5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [35]:
df.describe()

Column1   Column2   Column3   Column4
count  5.000000  5.000000  5.000000  5.000000
mean   0.618539 -0.934927 -0.564360 -0.567099
std    1.024627  1.087636  0.648503  1.515737
min   -0.817751 -2.679288 -1.180192 -1.973805
25%    0.113475 -1.159130 -0.971657 -1.886787
50%    0.649122 -0.719015 -0.917120 -0.457767
75%    1.408140 -0.226266 -0.058217 -0.266778
max    1.739710  0.109067  0.305388  1.749641

In [36]:
df.corr()

Column1   Column2   Column3   Column4
Column1  1.000000 -0.303675 -0.823618 -0.015603
Column2 -0.303675  1.000000  0.418588  0.673033
Column3 -0.823618  0.418588  1.000000  0.179246
Column4 -0.015603  0.673033  0.179246  1.000000